---
version: '3'
services:
  anayltic2-db:
    image: postgres:15-alpine
    environment:
      POSTGRES_DB: anayltic2
      POSTGRES_USER: anayltic2
      POSTGRES_PASSWORD: anayltic2
    ports:
      - '5432:5432'
    volumes:
      # - ./pg/sql/schema.postgresql.sql:/docker-entrypoint-initdb.d/schema.postgresql.sql:ro
      - ./volumesdata/pg/data:/var/lib/postgresql/data
    restart: always
  # notifications-redis:
  #   image: redis:6-alpine
  #   ports:
  #     - "6379:6379"
  #   volumes:
  #     - ./volumesdata/redis:/data
  #   restart: always
